### ISSUE TITLE
Content goes off-screen on a tablet

### ISSUE THREAD

**Issue by Arhell** [nunit/nunit.github.io#100]
![09-12-2021 00-21-27](https://user-images.githubusercontent.com/26163841/145294099-310927e5-19b2-4abe-b473-7015b9ea5a2e.jpg)
I'll fix it soon

**Comment by mikkelbu** [comment]
Thanks for reporting this @Arhell.

Please wait for a review before merging the PR. I can see that that this - unreviewed PRs - happens sometimes in this project, but the norm is to get anything reviewed before merging.
