### ISSUE TITLE
Copyright current year

### ISSUE THREAD

**Issue by Arhell** [nunit/nunit.github.io#102]
Do I need to update the year?
I can do it with js. сс @SeanKilleen

**Comment by SeanKilleen** [comment]
@rprouse -- checking in on this to make sure I've got it right.

These changes are for the NUnit site but as of now my area has been constrained to the docs.

If you'd like me to review and assist with these PRs on the site, I'm happy to. Just wanted to make sure you'd like me to proceed in that capacity first. 👍

**Comment by rprouse** [comment]
@SeanKilleen feel free to review, I trust your judgement.

@Arhell updating with JS sounds like a good idea

**Comment by SeanKilleen** [comment]
@Arhell I'm thinking since the site is published with Jekyll, if possible we could use liquid formatting which would then update whenever the site is published. Saves the JS code and uses the tooling that the site has adopted.

Let me know your thoughts!

**Comment by CharliePoole** [comment]
"Do I need to update the year?" I assume you mean the copyright year for the web site in the footer? If yes, I think you do!

Since it only would need to be done once a year and is a trivial change, I'd say do what's easiest.
