### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.github.io#15]
The copyright is now to NUnit, switch to CC and put under @CharliePoole and @rprouse.

For CC, I would prefer Attribution-NonCommercial-ShareAlike so people can't turn the docs into a commercial book without the copyright holders' permissions. Sound good?

**Comment by CharliePoole** [comment]
That's what I had in mind.

**Comment by jnm2** [comment]
I like it.

**Comment by jnm2** [comment]
Can we make it `Copyright © 2017 Charlie Poole, Rob Prouse` instead of `Copyright © 2017, Charlie Poole, Rob Prouse` to match the other things we've done?

**Comment by rprouse** [comment]
Are you talking about the extra comma? Fine by me. We can do it with the next update

**Comment by jnm2** [comment]
Yes.
