### ISSUE TITLE
Legacy Docs: Content overlap

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.github.io#17]
With 'wide' docs pages, the side menu can sometimes overlap the content. See below:

http://nunit.github.io/docs/2.4.8/collectionConstraints.html
![image](https://user-images.githubusercontent.com/4837132/27761164-d722a0b6-5e4e-11e7-85a7-021174a2111c.png)

Hopefully there's a simple CSS change - although afraid I'm not the person to supply that!

**Comment by CharliePoole** [comment]
If you compare it to http://nunit.org/index.php?p=collectionConstraints&r=2.4.8 there are two differences

1. The table doesn't limit itself in width and doesn't have the styling it has in the original.

2. The sidebar menu is not at the right of the screen.

This is css, specifically `nunit.css`. 

@rprouse You had me change the `#content` id to `#help_content`, which I did. But `nunit.css`, which your headers all reference, doesn't know about `#help_content`. 

My suggestion is to move `nunit.css` to a central location, reference that in the headers and edit it to match your content id.
