### ISSUE TITLE
Legacy Docs: Language picker broken

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.github.io#18]
![image](https://user-images.githubusercontent.com/4837132/27761180-148a36b2-5e4f-11e7-95d3-3c04c2f104ab.png)

We can just strip them all out - the code samples look find just one under each other.

**Comment by ChrisMaddock** [comment]
See #20 for ongoing discussion of how to handle this issue. Essentially, if anyone's interested in fixing this - great. If not, we may just remove them instead

**Comment by CharliePoole** [comment]
Also #17. My guess is that a number of things will start working if the CES for elements under #content starts being used again. Since it's a global fix I was figuring @rprouse had to do it at this point.
