### ISSUE TITLE
Fix HTTPS certificate issue for nunit.org and make all redirects go to HTTPS

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit.github.io#21]
Besides being professional, and more recently, a basic expectation of how the web always should have been ([puts it well](https://https.cio.gov/everything/)), HTTPS is especially important because we have download links to executables people run. Even if the download link uses HTTPS, that means nothing if the page itself is not loaded 100% over HTTPS.

As found by Ivan Pozdeev: https://nunit.org/ gives an HTTPS error because the  certificate is only valid for *.github.com, github.com, *.github.io, and github.io.

Also I see that https://nunit.com redirects to http://nunit.org. All redirects should be HTTPS and any site hit via HTTP should redirect to HTTPS.

**Comment by jnm2** [comment]
https://nunit.org/ gives an HTTPS error because the  certificate is only valid for *.github.com, github.com, *.github.io, and github.io.

Also, https:/nunit.com redirects to http://nunit.org. All redirects should be HTTPS and any site hit via HTTP should redirect to HTTPS.

**Comment by CharliePoole** [comment]
@jnm2 I have changed the redirection for nunit.net and nunit.com to use https.

I'm not clear what is meant by the hardfix label. I've been using it for stuff on the scope of "implement parallel execution of tests." This sounds like we just have to change a setting and edit some html files.

**Comment by jnm2** [comment]
Hmm, feel free to update it then. I assumed it would be hard to obtain and install a custom certificate valid for all our domain names, indeed possibly expensive unless the .NET Foundation helped out. Ive never run a github.io site.

https://nunit.com is still redirecting to non-https nunit.org. Which is good until we get the custom cert because right now browsers stop people from seeing https://nunit.org because of the cert problem.

**Comment by rprouse** [comment]
So far, in the help docs, it says you can enforce HTTPS for github.io sites. It also states that `HTTPS is not supported for GitHub Pages using custom domains.`, thus the `hardfix` label is valid. https://help.github.com/articles/securing-your-github-pages-site-with-https/

It is less desirable, but maybe we can redirect HTTPS to HTTP? Otherwise, we might want to consider other hosting.

**Comment by jnm2** [comment]
Ah, if you don't mind using CloudFlare, we can keep the hosting and do this for free: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by rprouse** [comment]
That is an excellent workaround, thank you @jnm2 

I would prefer to hold off on this a bit though. We are planning on joining the .NET Foundation and they can help us with SSL Certs.

**Comment by jnm2** [comment]
Relevant: https://www.troyhunt.com/life-is-about-to-get-harder-for-websites-without-https/

**Comment by rprouse** [comment]
HTTPS is now available for GitHub pages with custom domains, https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Enabling just requires we switch from using DNS A records to CNAME or ALIAS which I am doing now. Once I've tested and it is working, I will enforce HTTPS which will cause people going to HTTP to be automatically redirected.

**Comment by rprouse** [comment]
DNS has been updated, just waiting for it to propagate so that I can test.

**Comment by 304NotModified** [comment]
I think this one could be closed?

**Comment by ChrisMaddock** [comment]
Done in https://github.com/nunit/nunit.github.io/issues/62
