### ISSUE TITLE
Import legacy documentation

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.github.io#4]
This could be experimental, but can we pull in the legacy document partials and then write an index.php that uses Javascript to load the docs? Will index.php be treated as html on github.io?

**Comment by CharliePoole** [comment]
I'm converting to static HTML. See nunit/nunit.org#57. 

The capability is part of my homebrew PHP setup.

**Comment by jnm2** [comment]
I have a preference for static HTML whenever possible.

**Comment by rprouse** [comment]
@CharliePoole I am ready to experiment with the exported HTML for the docs when you have time to do the export. Ideally without headers. You can email me a zip or attach to this issue. Thanks.

I could also try to use the existing html fragements although I think I will need to recreate the menus.

**Comment by CharliePoole** [comment]
I'll just do a temporary adhoc fix to the software to not put out the headers and footers. If we're lucky I'll get to it this evening.

**Comment by CharliePoole** [comment]
Too tired tonight - I'll do it in the morning. Here is a question to speed things along...

My template looks like this...

```PHP
<?php getHeader(); ?>

<div id="content">

<?php include ( currentPageDirectory() . currentPageName() . ".html" ); ?>

</div>

<?php if ( file_exists( currentPageDirectory() . "sub_menu.txt" ) ) getSidebar(); ?>

<?php getFooter(); ?>
```

The `include` line gets you the expanded html fragment. But I think you need the menu for the docs as well, which is in the sidebar. So I would give you the content div and the sidebar div. Does that make sense?

**Comment by rprouse** [comment]
Content and sidebar would be perfect, but can you rename content to help_content? If the generator is in the website, I could do it too.

**Comment by CharliePoole** [comment]
Running the generator on the website runs into issues with permissions. I always run it on my localhost. I'll do it as soon as I finish my morning coffee. 😄

**Comment by rprouse** [comment]
I tried creating a simple `index.php` on the GitHub website and it didn't work. It isn't treated as a web page, it is downloaded, so my idea of maintaining the URI's won't work. I am going to google to see if I can set the mime type for pages.

**Comment by rprouse** [comment]
I've made some progress. I worked around not being able to serve up `index.php` by creating a directory of that name and dropping an `index.html` file into it. I then added some JavaScript to parse the query string and I can do that, so I think we are good to go. Hopefully the links in the generated docs will be usable and we will need to update existing links, but I think this may be doable.

If the resulting docs have predictable names, I can fetch them based on the query string and insert them into the DOM.

Testing with the URI, http://localhost:4000/index.php?p=releaseNotes&r=2.5.9

![image](https://user-images.githubusercontent.com/493828/27742612-56127482-5d87-11e7-9682-de32240fe2a6.png)

**Comment by CharliePoole** [comment]
Frankly, you seem to be doing a lot of work to avoid continued use of the existing host. You could easily change the look and feel on that host, or you could simply leave the legacy docs there and let it look like it looks! 

At any rate, I'll have the files for you shortly.

**Comment by CharliePoole** [comment]
Sent the files...

**Comment by rprouse** [comment]
My issue with the existing host is that it is PHP based which most .NET developers don't have installed making it hard to test changes locally. I guess that isn't much different than having to have Ruby installed, but at least it doesn't require Apache or IIS too. Getting up and running with this implementation only took a few minutes compared to setting up a LAMP stack.

**Comment by CharliePoole** [comment]
Sure... it's only a problem if your redirection doesn't work. It sounds a bit labored. 

If you left legacy docs on the old server, without changing the look, then nobody would ever update it. This is the first time I've updated any php in about five years. If you wanted to duplicate the look, that would take more knowledge.

**Comment by rprouse** [comment]
The redirect works and I had some fun this afternoon pretending I'm a front-end web dev 😄
