### ISSUE TITLE
Remove or update donations link

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit.github.io#43]
I just noticed that the donations link is still active and pointing to the account I use for payments to my business. Can we get this deactivated or switched? All that is needed is for somebody to set up a paypal account for the NUnit Project and change the button to use that link.

**Comment by CharliePoole** [comment]
Fallback... If we can't decide by the end of the year, I'll take this issue and do a PR to disable the link for the time being.

**Comment by rprouse** [comment]
For now, let's comment out the button on the page. I am not against taking donations, but when StickerYou offered us money, the team was hesitant taking it. Let's wait until we finish the transition to the .NET Foundation to decide, they may have accounts that we could use for the donations.

**Comment by CharliePoole** [comment]
@rprouse I messed up and pushed to master rather than to a branch! Please take a look at the donations page and see if you want the wording changed in any way. Also added a missing contributor to the list.

**Comment by rprouse** [comment]
Looks good, thanks for doing that. I will leave this open so that we can decide what to do about donations when we are ready. I'm also going to lock master on that repo 😄

**Comment by 304NotModified** [comment]
> Currently, financial contributions to NUnit are suspended while we complete our reorganization under the .NET Foundation.

I think this is done already ;)  Could you please update the page? (and I guess this issue could be closed then)

**Comment by rprouse** [comment]
@nunit/core-team do we want to pick up the conversation here? At the moment, I think I would prefer to link to past contributors, but not accept contributions. I am open to accepting contributions, but we need to figure out what to use them for and how to distribute them.

**Comment by ChrisMaddock** [comment]
I agree that is a good interim measure.

**Comment by jnm2** [comment]
Sounds good.
