### ISSUE TITLE
Transfer nunit.org and nunit.net domains

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit.github.io#44]
These are coming up for renewal on 3/29 and 4/29 respectively. It's not too soon to do something! As a preliminary step I propose to set up a separate account with GoDaddy for the NUnit Project and move the domains to that account. That doesn't require action by anyone but myself and if we don't do a transfer of registrar before the renewal date, I can simply change the name on that account to Rob or to whomever else is appropriate.

Alternatively, if we actually know where the registration is to go, we could that process directly. I'd like to get something going now because transfers sometimes take a while and names can be lost in the process - it's happened to me with one other group when the baton was being passed.

**Comment by CharliePoole** [comment]
It has been suggested that we transfer the domains to the .NET Foundation. However, we don't know if they do that and need to find out. I assume that the Core Team would also have to vote on whether we want to give up ownership of the domains.

Fallback... if that isn't resolved by the end of the year, I will set up a new account at GoDaddy, separate from mine, in the name of The NUnit Project. I'll put my credit card on it if one is needed but will remove it from automatic renewal. I'll set it up so notices go to the Core Team members and give all of them access to the account.

I'm not particularly recommending that the account at GoDaddy be maintained. It's just that this is a fallback action I can take entirely on my own. Transfers between registrars often take a while to accomplish, whereas transfer to a new account at GoDaddy will be pretty much instantaneous.

**Comment by CharliePoole** [comment]
If Gandi.net works like others I've used, you will probably need to initiate the transfer of the domain to their registration and I'll be asked to confirm. To keep things simple, you may want to initially point the DNS to NS13.ACORNHOST.COM and NS14.ACORNHOST.COM. Then, once you set it up as you want in CPanel or other interface, you can repoint it and I can drop the Acorn account.

**Comment by CharliePoole** [comment]
@rprouse Any movement on getting this transfer started?

**Comment by rprouse** [comment]
No, sorry. We had a release going out just before Christmas at work. I have a week and a half off now. I will try to get to it once Christmas is past.

**Comment by rprouse** [comment]
I tried to initiate the transfer today, but got the error `The domain's whois data shows that it has the Transfer Prohibited status` for both domains. I think you need to enable transfer @CharliePoole.

**Comment by CharliePoole** [comment]
Unlocked... wait a bit and try again.

**Comment by rprouse** [comment]
I've initiated transfer. I think you will receive an email and then I will need a verification code.

**Comment by rprouse** [comment]
Transfer failed because I need a transfer authorization code for each domain. I thought that was second step, but needed for first step. @CharliePoole can you get those codes? Mail them to me so they aren't public.

**Comment by rprouse** [comment]
Closing, the two domains are successfully transferred. Working on the DNS next.

**Comment by CharliePoole** [comment]
As a follow-up to this and #45, the NUnit hosting account at Acorn host is now closed.
