### ISSUE TITLE
Move DNS for nunit domains

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit.github.io#45]
Acornhost is where I previously hosted the site and the DNS is still there. We don't actually use it for anything except DNS and (I believe) one email address. I propose to move it either to GoDaddy if the registration remains there or elsewhere if we know where it should be at this time.

This is related to issue #44 but separate from it.

**Comment by CharliePoole** [comment]
Assigning myself but waiting for input.

**Comment by ChrisMaddock** [comment]
@rprouse - could both this and #44 be handed over to the .NET Foundation, or is that outside of their remit? I feel like that's the most sustainable option. 🙂

**Comment by CharliePoole** [comment]
That's OK with me... BUT...

These things have needed doing for a while. There was a governance issue, I think about a year ago, and the core team decided to postpone. As the person who is waiting for #43, #44 and #45, I'm getting a bit impatient, so I escalated it to the point of creating issues. I don't like putting myself in conflict with the rest of the team over this stuff, but there are specific effects on me (and on us) due to my continuing to handle them. If I were able to deal with both ends of it, I'd feel less pressure, but the contact with .NET foundation is centralized. That's probably for good reason but it leaves me waiting with no info other than "Maybe the Foundation can eventually do it."

I need to get out of that state of uncertainty, which is why I've stated a fallback for two of the three issues and will come up with one for the third. I feel like I need to start carrying out the fallbacks by the end of the year.

**Comment by CharliePoole** [comment]
Fallback plan for this issue... By the end of the year, if nothing has happened to change things, I will move the DNS to a GoDaddy account (free DNS) and cancel the nunit.org account I have at Acornhost. Prerequisite will be first completing the fallback on #44, q.v.

**Comment by ChrisMaddock** [comment]
That's reasonable.

Are you happy for us to contact the .NET Foundation, and see if we can get this sorted the 'long-term-plan' way immediately? And if not, or we don't get a timely response, we can set go ahead with the back up plan? @rprouse - you've had the most contact so far, would you be able to raise this?

**Comment by CharliePoole** [comment]
Definitely happy with that! Also happy to work with whomever does that sort of thing for the foundation if @rprouse gives the OK - and the contact. 😸

**Comment by rprouse** [comment]
For now, how about we transfer the domains to my NIC handle on Gandi.net and I will manage the DNS. I will get you the info soon. Assigning this issue to me.

**Comment by CharliePoole** [comment]
That's great... #44 comes first, obviously, and can be done separately, leaving the DNS with Acorn until you change it. In that case, I wouldn't have anything to do on this one except cancel the Acorn account when it's no longer needed.

**Comment by rprouse** [comment]
I would like it to go to the foundation, but I think Jon is overworked and doesn't have enough help, so I will take it for now.

**Comment by rprouse** [comment]
DNS is switched over for the two domains. I will close this issue once I see it propogate and once I see that there are no errors. Timeout for the old `NS` records is 6 hours, so I should be able to check the changes by 20:00 EST today. `dig nunit.org any` is still showing the old records for me.

**Comment by CharliePoole** [comment]
Following up on this... My charliepoole.org site is currently forwarding nunit.com to nunit.org. I'll keep on doing this until I decide exactly how to use it.
