### ISSUE TITLE
Move legacy downloads

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.github.io#5]
The current NUnit.org site hosts the downloads of all the old versions of NUnit. These need to be move elsewhere and the links updated. One option is to move them to backdated releases in the NUnit 2 github repository.

**Comment by CharliePoole** [comment]
Another is to leave them where they are.

**Comment by rprouse** [comment]
> Another is to leave them where they are.

Do you mean physically where they are and give them a new sub-domain? If this repo is going to be the new nunit.org website, then I believe all content needs to be in the repo and I don't think I want all those binaries in the repo. I could be wrong about binary files in github.io sites though...

**Comment by OsirisTerje** [comment]
github.io is just a rendering of a standard git repository, particularly well suited for markdown files (or static files in general).  So binary files should not go there, better then drop those into some static archive repo

**Comment by CharliePoole** [comment]
@rprouse So you can't have binary files in a downloads or ftp directory if the site is on GitHub? If that's a restriction they have imposed, then you put them elsewhere and change the links. One elsewhere is where they are... you we keep the nunit.org account with AcornHost for $4 per month but we set it up so that it only responds to that directory.

Your nameservers come before your web site. So nunit.org would point to GitHub, while ftp.nunit.org would point to AcornHost. As mentioned elsewhere, you can do the same thing with the docs, provided you are willing to use something like legacy.nunit.org.

**Comment by OsirisTerje** [comment]
It is not really a "site", it is a rendering engine on top of a git repository.  SO linking to something else would be good, but that "else" could be  a "static" git repo on github too, one which we dont need to change so  often

**Comment by jnm2** [comment]
The only benefit to keeping the binaries in a separate repo that I can see is for the sake of quick forking and cloning. :+1:

**Comment by CharliePoole** [comment]
I'll stay out of the discussion of how to handle it on GitHub, but I can certainly keep them while you decide.

**Comment by rprouse** [comment]
I am in the process of adding all the legacy downloads to this site. Even though they are all archived on the NUnit.org webserver, none of the links point to those archives. Instead, all point to SourceForge, LaunchPad.net and GitHub.

Based on this, I don't think there is anything to do for this issue except add the links to the download page on this site which I am doing now.

**Comment by CharliePoole** [comment]
I always considered them as backups to the public downloads. Over the years, I think I made the downloads available twice, when the normal download location was unavailable. Still, it seems good to have them.

**Comment by rprouse** [comment]
Good point on backup, but at least they won't be blocking updating this website. I will figure out a place to archive them permenantly

**Comment by ChrisMaddock** [comment]
This looks done to me, thanks Rob! 🙂
