### ISSUE TITLE
Decide about Donations

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.github.io#6]
The main NUnit site has a donations button and donations page. This was mirrored on the GitHub page. The donations currently go to @CharliePoole to pay for hosting and domains. The @nunit/core-team should decide if we want to continue this and if so where the money should go. This might belong in the governance repo, but I put this here since it needs to be maintained or removed from the website.

I am fine to leave it up for now, but I don't need the money for hosting. If we keep it, I would prefer the money go to stickers for swag for @nunit/core-team members to give out at conferences and user groups.

No rush on this decision, I have update the page to add the recent donors, the donate button still works on the new page and @CharliePoole is still paying for hosting, DNS, etc.

**Comment by jnm2** [comment]
I think we should continue donations. Some people can't contribute other ways.

Does the decision to join the .NET Foundation have anything to do with this decision?

This just crossed my mind- would anyone be open to the possibility of taking a portion of that and splitting it between team members who are active in the key projects according to a fair and simple rule as a thank you for contributing and an incentive to stay active?

**Comment by ChrisMaddock** [comment]
> I am fine to leave it up for now, but I don't need the money for hosting. If we keep it, I would prefer the money go to stickers for swag for @nunit/core-team members to give out at conferences and user groups.

This sounds sensible to me.

**Comment by ChrisMaddock** [comment]
I'm doing a little organising in the nunit.github.io repo - I'm going to move this to governance - as I think it's first an issue for the Core Team to decide what action to take.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/governance #25](https://github.com/nunit/governance/issues/25) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CharliePoole** [comment]
Good idea to move this. I'm hoping for a decision soon. The new site makes it a bit more prominent than it was and it's silly to use it as one of the three highlights of home page unless you want them. Even sillier to keep sending them to me. :smile:
