### ISSUE TITLE
repo url to https

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit.github.io#61]
Please change the url of the repo to https :)

It should be http**s**://nuget.org, **not** https://**www**.nuget.org

![image](https://user-images.githubusercontent.com/5808377/52538170-a38c2000-2d6f-11e9-98d1-9027916c1bf3.png)

related: https://github.com/nunit/nunit/issues/3161

**Comment by 304NotModified** [comment]
bump @ChrisMaddock

**Comment by CharliePoole** [comment]
@rprouse ?
