### ISSUE TITLE
Please enable "Enforce HTTPS" for nunit.org

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit.github.io#62]
Https://nunit.org is working great!

It would be nice if https is enforced. You could configure that in github:

In the section "options"

![image](https://user-images.githubusercontent.com/5808377/52540128-64b59480-2d86-11e9-92d2-61eaaac073a6.png)

there is below an option "Enforce HTTPS"

![image](https://user-images.githubusercontent.com/5808377/52540133-6ed79300-2d86-11e9-8b58-1d2add92ca1d.png)

Please enable it. Related: #21 (I think that one could be closed)

**Comment by rprouse** [comment]
Before we enforce Https I want to make sure existing http links will be properly redirected. There are a lot of links into the legacy docs.

**Comment by 304NotModified** [comment]
the enforce will redirect http to https, it will not disable http or something like that. So for legacy, enforce is really recommend. ;)

**Comment by ChrisMaddock** [comment]
My understanding is also that GitHub pages will 'by default' do a transparant redirect. Ref here: https://help.github.com/en/articles/securing-your-github-pages-site-with-https

I'd be keen for the site to go full https as well. 🙂

**Comment by ChrisMaddock** [comment]
Hey @rprouse,

Would you mind revisiting this one? It seems like a we can check fairly easily if it's working as we want or not, and also revert easily if there's problems. 

Let me know if I can help at all - this is an issue I'm keen on. 😄

**Comment by rprouse** [comment]
Done and it seems to be working. I was worried about old links like http://www.nunit.org/docs/2.5.5/attributes.html not redirecting properly because https://www.nunit.org does not have a proper certificate, but it properly redirects to the HTTPS non-www page.

**Comment by ChrisMaddock** [comment]
Awesome! Thanks rob! :-D
