### ISSUE TITLE
Netlify build for site?

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/nunit.github.io#99]
seeing #98, I realized there's not currently any way to see a quick preview of changes.

If I have the right access -- and I think I might? -- I can add Netlify to the solution and hook it here as a check. Will catch and build errors plus let us see a preview of each PR, and will do so for free since the repo is public.

Let me know if it would be helpful.

**Comment by Arhell** [comment]
Of course you can, I don't mind. Since the site is on jekyll it will be easy.

**Comment by SeanKilleen** [comment]
Yep! This is more a question for @rprouse.

**Comment by rprouse** [comment]
Huge thumbs up for this!

**Comment by SeanKilleen** [comment]
Updates on this:

* I've applied to Netlify for an OSS team, which provides for an allowance of free minutes etc. for an OSS project.
* Separately, I've authorized Netlify for this repo under my own Netlify account. Builds etc. will use the free minutes on my Netlify account. Once we get the OSS Account, I'll transfer this over there and add others.
